
#These configs are general configs that don't fit any other category.
[general]
	#Do dogs spawn into the world lying down if they are already sitting.
	dogsSpawnLying = true
	#Time to spend sitting (in ticks) before dogs lie down.
	#Range: 1 ~ 6000000
	timeBeforeLie = 300
	#Range for target to get to dog before dog gets up (in blocks)
	#Range: 0.0 ~ 32.0
	rangeBeforeGettingUp = 3.0
	#Who the dog gets up for?
	#Accepts: NOBODY, OWNER, PLAYERS, ANY_LIVING_ENTITY
	#Allowed Values: NOBODY, OWNER, PLAYERS, ANY_LIVING_ENTITY
	getsUpFor = "OWNER"
	#Play a bark/whine when the dog stands up/lies down?
	playSoundWhenLieStateChanges = true
	#Poses for lying down that are enabled. If the mod can't find compatible poses, it will randomly pick one set.
	enabledPoses = ["forelegStraight", "forelegSprawled", "forelegSprawledBack", "forelegSkewed", "forelegSide", "hindlegStraight", "hindlegStraightBack", "hindlegSprawled", "hindlegSprawledBack", "hindlegSide"]

